#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FlexyPark.UI.Droid.Resource", IsApplication=true)]

namespace FlexyPark.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::FlexyPark.UI.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::FlexyPark.UI.Droid.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::FlexyPark.UI.Droid.Resource.String.library_name;
			global::Xamarin.InAppBilling.Resource.String.library_name = global::FlexyPark.UI.Droid.Resource.String.library_name;
			global::Stripe.Resource.Drawable.amex = global::FlexyPark.UI.Droid.Resource.Drawable.amex;
			global::Stripe.Resource.Drawable.credit = global::FlexyPark.UI.Droid.Resource.Drawable.credit;
			global::Stripe.Resource.Drawable.cvc = global::FlexyPark.UI.Droid.Resource.Drawable.cvc;
			global::Stripe.Resource.Drawable.diners = global::FlexyPark.UI.Droid.Resource.Drawable.diners;
			global::Stripe.Resource.Drawable.discover = global::FlexyPark.UI.Droid.Resource.Drawable.discover;
			global::Stripe.Resource.Drawable.jcb = global::FlexyPark.UI.Droid.Resource.Drawable.jcb;
			global::Stripe.Resource.Drawable.maestro = global::FlexyPark.UI.Droid.Resource.Drawable.maestro;
			global::Stripe.Resource.Drawable.mastercard = global::FlexyPark.UI.Droid.Resource.Drawable.mastercard;
			global::Stripe.Resource.Drawable.visa = global::FlexyPark.UI.Droid.Resource.Drawable.visa;
			global::Stripe.Resource.Id.stripeCvc = global::FlexyPark.UI.Droid.Resource.Id.stripeCvc;
			global::Stripe.Resource.Id.stripeExpiration = global::FlexyPark.UI.Droid.Resource.Id.stripeExpiration;
			global::Stripe.Resource.Id.stripeImage = global::FlexyPark.UI.Droid.Resource.Id.stripeImage;
			global::Stripe.Resource.Id.stripeLastFour = global::FlexyPark.UI.Droid.Resource.Id.stripeLastFour;
			global::Stripe.Resource.Id.stripeLayoutOne = global::FlexyPark.UI.Droid.Resource.Id.stripeLayoutOne;
			global::Stripe.Resource.Id.stripeLayoutTwo = global::FlexyPark.UI.Droid.Resource.Id.stripeLayoutTwo;
			global::Stripe.Resource.Id.stripeNumber = global::FlexyPark.UI.Droid.Resource.Id.stripeNumber;
			global::Stripe.Resource.Layout.stripeviewlayout = global::FlexyPark.UI.Droid.Resource.Layout.stripeviewlayout;
			global::Stripe.Resource.String.library_name = global::FlexyPark.UI.Droid.Resource.String.library_name;
			global::MonoDroid.TimesSquare.Resource.Attribute.dayBackground = global::FlexyPark.UI.Droid.Resource.Attribute.dayBackground;
			global::MonoDroid.TimesSquare.Resource.Attribute.dayTextColor = global::FlexyPark.UI.Droid.Resource.Attribute.dayTextColor;
			global::MonoDroid.TimesSquare.Resource.Attribute.dividerColor = global::FlexyPark.UI.Droid.Resource.Attribute.dividerColor;
			global::MonoDroid.TimesSquare.Resource.Attribute.headerTextColor = global::FlexyPark.UI.Droid.Resource.Attribute.headerTextColor;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_current_month = global::FlexyPark.UI.Droid.Resource.Attribute.state_current_month;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_highlighted = global::FlexyPark.UI.Droid.Resource.Attribute.state_highlighted;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_range_first = global::FlexyPark.UI.Droid.Resource.Attribute.state_range_first;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_range_last = global::FlexyPark.UI.Droid.Resource.Attribute.state_range_last;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_range_middle = global::FlexyPark.UI.Droid.Resource.Attribute.state_range_middle;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_selectable = global::FlexyPark.UI.Droid.Resource.Attribute.state_selectable;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_today = global::FlexyPark.UI.Droid.Resource.Attribute.state_today;
			global::MonoDroid.TimesSquare.Resource.Attribute.titleTextColor = global::FlexyPark.UI.Droid.Resource.Attribute.titleTextColor;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_active_month_bg = global::FlexyPark.UI.Droid.Resource.Color.calendar_active_month_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_bg = global::FlexyPark.UI.Droid.Resource.Color.calendar_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_divider = global::FlexyPark.UI.Droid.Resource.Color.calendar_divider;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_highlighted_day_bg = global::FlexyPark.UI.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_inactive_month_bg = global::FlexyPark.UI.Droid.Resource.Color.calendar_inactive_month_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_selected_day_bg = global::FlexyPark.UI.Droid.Resource.Color.calendar_selected_day_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_selected_range_bg = global::FlexyPark.UI.Droid.Resource.Color.calendar_selected_range_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_active = global::FlexyPark.UI.Droid.Resource.Color.calendar_text_active;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_inactive = global::FlexyPark.UI.Droid.Resource.Color.calendar_text_inactive;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_selected = global::FlexyPark.UI.Droid.Resource.Color.calendar_text_selected;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_selector = global::FlexyPark.UI.Droid.Resource.Color.calendar_text_selector;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_unselectable = global::FlexyPark.UI.Droid.Resource.Color.calendar_text_unselectable;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_today_bg = global::FlexyPark.UI.Droid.Resource.Color.calendar_today_bg;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_day_headers_paddingbottom = global::FlexyPark.UI.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_month_title_bottommargin = global::FlexyPark.UI.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_month_topmargin = global::FlexyPark.UI.Droid.Resource.Dimension.calendar_month_topmargin;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_text_medium = global::FlexyPark.UI.Droid.Resource.Dimension.calendar_text_medium;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_text_small = global::FlexyPark.UI.Droid.Resource.Dimension.calendar_text_small;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBase = global::FlexyPark.UI.Droid.Resource.Dimension.marginBase;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBase_5 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBase_5;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBase_6 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBase_6;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex10 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex10;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex11 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex11;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex12 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex12;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex13 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex13;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex14 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex14;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex15 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex15;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex18 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex18;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex2 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex2;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex20 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex20;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex22 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex22;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex23 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex23;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex25 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex25;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex27 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex27;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex3 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex3;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex3_5 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex3_5;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex30 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex30;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex35 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex35;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex4 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex4;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex40 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex40;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex45 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex45;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex5 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex5;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex50 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex50;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex55 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex55;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex6 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex6;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex60 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex60;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex7 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex7;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex8 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex8;
			global::MonoDroid.TimesSquare.Resource.Dimension.marginBasex9 = global::FlexyPark.UI.Droid.Resource.Dimension.marginBasex9;
			global::MonoDroid.TimesSquare.Resource.Dimension.menu_width = global::FlexyPark.UI.Droid.Resource.Dimension.menu_width;
			global::MonoDroid.TimesSquare.Resource.Dimension.textBig = global::FlexyPark.UI.Droid.Resource.Dimension.textBig;
			global::MonoDroid.TimesSquare.Resource.Dimension.textBigger = global::FlexyPark.UI.Droid.Resource.Dimension.textBigger;
			global::MonoDroid.TimesSquare.Resource.Dimension.textExtraLarge = global::FlexyPark.UI.Droid.Resource.Dimension.textExtraLarge;
			global::MonoDroid.TimesSquare.Resource.Dimension.textExtraSmall = global::FlexyPark.UI.Droid.Resource.Dimension.textExtraSmall;
			global::MonoDroid.TimesSquare.Resource.Dimension.textHeader = global::FlexyPark.UI.Droid.Resource.Dimension.textHeader;
			global::MonoDroid.TimesSquare.Resource.Dimension.textLarge = global::FlexyPark.UI.Droid.Resource.Dimension.textLarge;
			global::MonoDroid.TimesSquare.Resource.Dimension.textMedium = global::FlexyPark.UI.Droid.Resource.Dimension.textMedium;
			global::MonoDroid.TimesSquare.Resource.Dimension.textMediumBig = global::FlexyPark.UI.Droid.Resource.Dimension.textMediumBig;
			global::MonoDroid.TimesSquare.Resource.Dimension.textMediumLarge = global::FlexyPark.UI.Droid.Resource.Dimension.textMediumLarge;
			global::MonoDroid.TimesSquare.Resource.Dimension.textSmall = global::FlexyPark.UI.Droid.Resource.Dimension.textSmall;
			global::MonoDroid.TimesSquare.Resource.Dimension.textXXSmall = global::FlexyPark.UI.Droid.Resource.Dimension.textXXSmall;
			global::MonoDroid.TimesSquare.Resource.Drawable.calendar_bg_selector = global::FlexyPark.UI.Droid.Resource.Drawable.calendar_bg_selector;
			global::MonoDroid.TimesSquare.Resource.Id.calendar_grid = global::FlexyPark.UI.Droid.Resource.Id.calendar_grid;
			global::MonoDroid.TimesSquare.Resource.Id.title = global::FlexyPark.UI.Droid.Resource.Id.title;
			global::MonoDroid.TimesSquare.Resource.Layout.month = global::FlexyPark.UI.Droid.Resource.Layout.month;
			global::MonoDroid.TimesSquare.Resource.Layout.week = global::FlexyPark.UI.Droid.Resource.Layout.week;
			global::MonoDroid.TimesSquare.Resource.String.day_name_format = global::FlexyPark.UI.Droid.Resource.String.day_name_format;
			global::MonoDroid.TimesSquare.Resource.String.full_date_format = global::FlexyPark.UI.Droid.Resource.String.full_date_format;
			global::MonoDroid.TimesSquare.Resource.String.invalid_date = global::FlexyPark.UI.Droid.Resource.String.invalid_date;
			global::MonoDroid.TimesSquare.Resource.String.library_name = global::FlexyPark.UI.Droid.Resource.String.library_name;
			global::MonoDroid.TimesSquare.Resource.String.month_name_format = global::FlexyPark.UI.Droid.Resource.String.month_name_format;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarCell = global::FlexyPark.UI.Droid.Resource.Style.CalendarCell;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarCell_CalendarDate = global::FlexyPark.UI.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarCell_DayHeader = global::FlexyPark.UI.Droid.Resource.Style.CalendarCell_DayHeader;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarTitle = global::FlexyPark.UI.Droid.Resource.Style.CalendarTitle;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView = global::FlexyPark.UI.Droid.Resource.Styleable.CalendarPickerView;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_android_background = global::FlexyPark.UI.Droid.Resource.Styleable.CalendarPickerView_android_background;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_dayBackground = global::FlexyPark.UI.Droid.Resource.Styleable.CalendarPickerView_dayBackground;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_dayTextColor = global::FlexyPark.UI.Droid.Resource.Styleable.CalendarPickerView_dayTextColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_dividerColor = global::FlexyPark.UI.Droid.Resource.Styleable.CalendarPickerView_dividerColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_headerTextColor = global::FlexyPark.UI.Droid.Resource.Styleable.CalendarPickerView_headerTextColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_titleTextColor = global::FlexyPark.UI.Droid.Resource.Styleable.CalendarPickerView_titleTextColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_current_month = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell_state_current_month;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_highlighted = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell_state_highlighted;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_range_first = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell_state_range_first;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_range_last = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell_state_range_last;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_range_middle = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell_state_range_middle;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_selectable = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell_state_selectable;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_today = global::FlexyPark.UI.Droid.Resource.Styleable.calendar_cell_state_today;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int Dialog_Bottom_To_Top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Dialog_Top_To_Bottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fade_in_animation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fade_out_animation = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_in_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_in_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_out_left = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_out_right = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010039
			public const int GroupItemTemplate = 2130772025;
			
			// aapt resource value: 0x7f010035
			public const int MvxBind = 2130772021;
			
			// aapt resource value: 0x7f010038
			public const int MvxDropDownItemTemplate = 2130772024;
			
			// aapt resource value: 0x7f010037
			public const int MvxItemTemplate = 2130772023;
			
			// aapt resource value: 0x7f010036
			public const int MvxLang = 2130772022;
			
			// aapt resource value: 0x7f01003a
			public const int MvxSource = 2130772026;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f01003f
			public const int centered = 2130772031;
			
			// aapt resource value: 0x7f010012
			public const int circleCrop = 2130771986;
			
			// aapt resource value: 0x7f010047
			public const int clipPadding = 2130772039;
			
			// aapt resource value: 0x7f010025
			public const int columnGap = 2130772005;
			
			// aapt resource value: 0x7f010014
			public const int dayBackground = 2130771988;
			
			// aapt resource value: 0x7f010029
			public const int dayBackgroundColor = 2130772009;
			
			// aapt resource value: 0x7f010031
			public const int dayNameLength = 2130772017;
			
			// aapt resource value: 0x7f010015
			public const int dayTextColor = 2130771989;
			
			// aapt resource value: 0x7f010013
			public const int dividerColor = 2130771987;
			
			// aapt resource value: 0x7f010033
			public const int eventMarginVertical = 2130772019;
			
			// aapt resource value: 0x7f01002f
			public const int eventPadding = 2130772015;
			
			// aapt resource value: 0x7f01002e
			public const int eventTextColor = 2130772014;
			
			// aapt resource value: 0x7f010022
			public const int eventTextSize = 2130772002;
			
			// aapt resource value: 0x7f010040
			public const int fillColor = 2130772032;
			
			// aapt resource value: 0x7f01001f
			public const int firstDayOfWeek = 2130771999;
			
			// aapt resource value: 0x7f010048
			public const int footerColor = 2130772040;
			
			// aapt resource value: 0x7f01004b
			public const int footerIndicatorHeight = 2130772043;
			
			// aapt resource value: 0x7f01004a
			public const int footerIndicatorStyle = 2130772042;
			
			// aapt resource value: 0x7f01004c
			public const int footerIndicatorUnderlinePadding = 2130772044;
			
			// aapt resource value: 0x7f010049
			public const int footerLineHeight = 2130772041;
			
			// aapt resource value: 0x7f01004d
			public const int footerPadding = 2130772045;
			
			// aapt resource value: 0x7f010030
			public const int headerColumnBackground = 2130772016;
			
			// aapt resource value: 0x7f010023
			public const int headerColumnPadding = 2130772003;
			
			// aapt resource value: 0x7f010026
			public const int headerColumnTextColor = 2130772006;
			
			// aapt resource value: 0x7f010028
			public const int headerRowBackgroundColor = 2130772008;
			
			// aapt resource value: 0x7f010024
			public const int headerRowPadding = 2130772004;
			
			// aapt resource value: 0x7f010017
			public const int headerTextColor = 2130771991;
			
			// aapt resource value: 0x7f010020
			public const int hourHeight = 2130772000;
			
			// aapt resource value: 0x7f01002a
			public const int hourSeparatorColor = 2130772010;
			
			// aapt resource value: 0x7f01002d
			public const int hourSeparatorHeight = 2130772013;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatio = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int imageAspectRatioAdjust = 2130771984;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010027
			public const int noOfVisibleDays = 2130772007;
			
			// aapt resource value: 0x7f010042
			public const int orientation = 2130772034;
			
			// aapt resource value: 0x7f010032
			public const int overlappingEventGap = 2130772018;
			
			// aapt resource value: 0x7f010041
			public const int pageColor = 2130772033;
			
			// aapt resource value: 0x7f010043
			public const int radius = 2130772035;
			
			// aapt resource value: 0x7f01004f
			public const int selectedBold = 2130772047;
			
			// aapt resource value: 0x7f01004e
			public const int selectedColor = 2130772046;
			
			// aapt resource value: 0x7f010044
			public const int snap = 2130772036;
			
			// aapt resource value: 0x7f010019
			public const int state_current_month = 2130771993;
			
			// aapt resource value: 0x7f01001e
			public const int state_highlighted = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int state_range_first = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int state_range_last = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int state_range_middle = 2130771996;
			
			// aapt resource value: 0x7f010018
			public const int state_selectable = 2130771992;
			
			// aapt resource value: 0x7f01001a
			public const int state_today = 2130771994;
			
			// aapt resource value: 0x7f010045
			public const int strokeColor = 2130772037;
			
			// aapt resource value: 0x7f010046
			public const int strokeWidth = 2130772038;
			
			// aapt resource value: 0x7f010050
			public const int textColor = 2130772048;
			
			// aapt resource value: 0x7f010051
			public const int textSize = 2130772049;
			
			// aapt resource value: 0x7f010021
			public const int textSizeX = 2130772001;
			
			// aapt resource value: 0x7f010052
			public const int titlePadding = 2130772050;
			
			// aapt resource value: 0x7f010016
			public const int titleTextColor = 2130771990;
			
			// aapt resource value: 0x7f01002b
			public const int todayBackgroundColor = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int todayHeaderTextColor = 2130772012;
			
			// aapt resource value: 0x7f010053
			public const int topPadding = 2130772051;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01003b
			public const int vpiCirclePageIndicatorStyle = 2130772027;
			
			// aapt resource value: 0x7f01003d
			public const int vpiTabPageIndicatorStyle = 2130772029;
			
			// aapt resource value: 0x7f01003e
			public const int vpiTabTextStyle = 2130772030;
			
			// aapt resource value: 0x7f01003c
			public const int vpiTitlePageIndicatorStyle = 2130772028;
			
			// aapt resource value: 0x7f010034
			public const int xScrollingSpeed = 2130772020;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0c0000
			public const int default_circle_indicator_centered = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int default_circle_indicator_snap = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int default_title_indicator_selected_bold = 2131492866;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070020
			public const int accent = 2131165216;
			
			// aapt resource value: 0x7f070016
			public const int bg = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int bg_lv = 2131165208;
			
			// aapt resource value: 0x7f07000a
			public const int calendar_active_month_bg = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int calendar_bg = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int calendar_divider = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int calendar_highlighted_day_bg = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int calendar_inactive_month_bg = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int calendar_selected_day_bg = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int calendar_selected_range_bg = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int calendar_text_active = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int calendar_text_inactive = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int calendar_text_selected = 2131165203;
			
			// aapt resource value: 0x7f070030
			public const int calendar_text_selector = 2131165232;
			
			// aapt resource value: 0x7f070014
			public const int calendar_text_unselectable = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int calendar_today_bg = 2131165205;
			
			// aapt resource value: 0x7f070009
			public const int common_action_bar_splitter = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int common_signin_btn_dark_text_default = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int common_signin_btn_dark_text_disabled = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_signin_btn_dark_text_focused = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_signin_btn_dark_text_pressed = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int common_signin_btn_default_background = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int common_signin_btn_light_text_default = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int common_signin_btn_light_text_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_signin_btn_light_text_focused = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int common_signin_btn_light_text_pressed = 2131165189;
			
			// aapt resource value: 0x7f070031
			public const int common_signin_btn_text_dark = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int common_signin_btn_text_light = 2131165234;
			
			// aapt resource value: 0x7f07002a
			public const int default_circle_indicator_fill_color = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int default_circle_indicator_page_color = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int default_circle_indicator_stroke_color = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int default_title_indicator_footer_color = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int default_title_indicator_selected_color = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int default_title_indicator_text_color = 2131165231;
			
			// aapt resource value: 0x7f07001a
			public const int event_color_01 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int event_color_02 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int event_color_03 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int event_color_04 = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int gray = 2131165217;
			
			// aapt resource value: 0x7f070017
			public const int header = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int text = 2131165209;
			
			// aapt resource value: 0x7f07001e
			public const int toolbar = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int toolbar_text = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int vpi__background_holo_dark = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int vpi__background_holo_light = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int vpi__bright_foreground_disabled_holo_dark = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int vpi__bright_foreground_disabled_holo_light = 2131165223;
			
			// aapt resource value: 0x7f070024
			public const int vpi__bright_foreground_holo_dark = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int vpi__bright_foreground_holo_light = 2131165221;
			
			// aapt resource value: 0x7f070028
			public const int vpi__bright_foreground_inverse_holo_dark = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int vpi__bright_foreground_inverse_holo_light = 2131165225;
			
			// aapt resource value: 0x7f070033
			public const int vpi__dark_theme = 2131165235;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int calendar_day_headers_paddingbottom = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int calendar_month_title_bottommargin = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int calendar_month_topmargin = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int calendar_text_medium = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int calendar_text_small = 2131296260;
			
			// aapt resource value: 0x7f090030
			public const int default_circle_indicator_radius = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int default_circle_indicator_stroke_width = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int default_title_indicator_clip_padding = 2131296306;
			
			// aapt resource value: 0x7f090034
			public const int default_title_indicator_footer_indicator_height = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int default_title_indicator_footer_indicator_underline_padding = 2131296309;
			
			// aapt resource value: 0x7f090033
			public const int default_title_indicator_footer_line_height = 2131296307;
			
			// aapt resource value: 0x7f090036
			public const int default_title_indicator_footer_padding = 2131296310;
			
			// aapt resource value: 0x7f090037
			public const int default_title_indicator_text_size = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int default_title_indicator_title_padding = 2131296312;
			
			// aapt resource value: 0x7f090039
			public const int default_title_indicator_top_padding = 2131296313;
			
			// aapt resource value: 0x7f090021
			public const int marginBase = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int marginBase_5 = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int marginBase_6 = 2131296291;
			
			// aapt resource value: 0x7f090017
			public const int marginBasex10 = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int marginBasex11 = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int marginBasex12 = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int marginBasex13 = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int marginBasex14 = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int marginBasex15 = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int marginBasex18 = 2131296273;
			
			// aapt resource value: 0x7f090020
			public const int marginBasex2 = 2131296288;
			
			// aapt resource value: 0x7f090010
			public const int marginBasex20 = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int marginBasex22 = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int marginBasex23 = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int marginBasex25 = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int marginBasex27 = 2131296268;
			
			// aapt resource value: 0x7f09001f
			public const int marginBasex3 = 2131296287;
			
			// aapt resource value: 0x7f09001e
			public const int marginBasex3_5 = 2131296286;
			
			// aapt resource value: 0x7f09000b
			public const int marginBasex30 = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int marginBasex35 = 2131296266;
			
			// aapt resource value: 0x7f09001d
			public const int marginBasex4 = 2131296285;
			
			// aapt resource value: 0x7f090009
			public const int marginBasex40 = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int marginBasex45 = 2131296264;
			
			// aapt resource value: 0x7f09001c
			public const int marginBasex5 = 2131296284;
			
			// aapt resource value: 0x7f090007
			public const int marginBasex50 = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int marginBasex55 = 2131296262;
			
			// aapt resource value: 0x7f09001b
			public const int marginBasex6 = 2131296283;
			
			// aapt resource value: 0x7f090005
			public const int marginBasex60 = 2131296261;
			
			// aapt resource value: 0x7f09001a
			public const int marginBasex7 = 2131296282;
			
			// aapt resource value: 0x7f090019
			public const int marginBasex8 = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int marginBasex9 = 2131296280;
			
			// aapt resource value: 0x7f09002f
			public const int menu_width = 2131296303;
			
			// aapt resource value: 0x7f090026
			public const int textBig = 2131296294;
			
			// aapt resource value: 0x7f090025
			public const int textBigger = 2131296293;
			
			// aapt resource value: 0x7f090028
			public const int textExtraLarge = 2131296296;
			
			// aapt resource value: 0x7f09002d
			public const int textExtraSmall = 2131296301;
			
			// aapt resource value: 0x7f090024
			public const int textHeader = 2131296292;
			
			// aapt resource value: 0x7f090029
			public const int textLarge = 2131296297;
			
			// aapt resource value: 0x7f09002b
			public const int textMedium = 2131296299;
			
			// aapt resource value: 0x7f090027
			public const int textMediumBig = 2131296295;
			
			// aapt resource value: 0x7f09002a
			public const int textMediumLarge = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int textSmall = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int textXXSmall = 2131296302;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int amex = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_scrubber_control_normal_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_while = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_corner_progress_dialog = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_cornor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_Dialog = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_edittext = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_recenter_cornor = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int blue_arrow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blue_icon_add = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int blue_icon_calendar = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int blue_icon_car = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int blue_icon_chart = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int blue_icon_checkmark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int blue_icon_euro = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int blue_icon_home = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int blue_icon_location = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int blue_icon_navigate = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int blue_icon_turnarrow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int blue_icon_turnarrow_gray = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int blue_icon_warning = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int blue_icon_warning_gray = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int calendar_bg_selector = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_full_open_on_phone = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_ic_googleplayservices = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_disabled_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_icon_disabled_focus_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_icon_disabled_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_icon_focus_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_icon_focus_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_icon_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_icon_normal_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_icon_normal_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_icon_pressed_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_icon_pressed_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_disabled_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_text_disabled_focus_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_signin_btn_text_disabled_focus_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_signin_btn_text_disabled_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_signin_btn_text_focus_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_signin_btn_text_focus_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_signin_btn_text_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_signin_btn_text_normal_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_signin_btn_text_normal_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_signin_btn_text_pressed_dark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_signin_btn_text_pressed_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int credit = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int custom_tab_indicator = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int custom_tab_indicator_focused = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int custom_tab_indicator_selected = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int custom_tab_indicator_selected_focused = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int custom_tab_indicator_selected_pressed = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int custom_tab_indicator_unselected = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int custom_tab_indicator_unselected_focused = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int custom_tab_indicator_unselected_pressed = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int cvc = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int diners = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int discover = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int green_icon_clock = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_plusone_medium_off_client = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_plusone_small_off_client = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_plusone_standard_off_client = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_plusone_tall_off_client = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Icon = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int icon_car = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int icon_credit = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int icon_home = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int icon_location = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ItemSelector = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ItemSelectorCornor = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int jcb = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ListSelector = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int maestro = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int mastercard = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int menu_credits = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int menu_myprofile = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int menu_ownparking = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int menu_parkme = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int menu_reservation = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int menu_settings = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int MenuBackground = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int powered_by_google_dark = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int powered_by_google_light = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int Selector_yes_no = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int shape = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int splashscreen = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int TabSelector = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int thumbSeekBar = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int toggle_no = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int toggle_yes = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int visa = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int vpi__tab_indicator = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int vpi__tab_selected_focused_holo = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int vpi__tab_selected_holo = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int vpi__tab_selected_pressed_holo = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int vpi__tab_unselected_focused_holo = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int vpi__tab_unselected_holo = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int vpi__tab_unselected_pressed_holo = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int white_icon_back = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int white_icon_clock = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int white_icon_delete = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int white_icon_edit_64 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int white_icon_menu = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int white_icon_next = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int white_icon_setting = 2130837611;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b006d
			public const int Message = 2131427437;
			
			// aapt resource value: 0x7f0b0001
			public const int MvxBindableListItemTagUnique = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int MvxBindingTagUnique = 2131427328;
			
			// aapt resource value: 0x7f0b0026
			public const int MvxListView = 2131427366;
			
			// aapt resource value: 0x7f0b0088
			public const int ParkMeLater = 2131427464;
			
			// aapt resource value: 0x7f0b0087
			public const int ParkMeNow = 2131427463;
			
			// aapt resource value: 0x7f0b002f
			public const int TextView3 = 2131427375;
			
			// aapt resource value: 0x7f0b006c
			public const int Title = 2131427436;
			
			// aapt resource value: 0x7f0b0007
			public const int adjust_height = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int adjust_width = 2131427336;
			
			// aapt resource value: 0x7f0b0097
			public const int button2 = 2131427479;
			
			// aapt resource value: 0x7f0b006e
			public const int calendar_grid = 2131427438;
			
			// aapt resource value: 0x7f0b005b
			public const int calendaritem = 2131427419;
			
			// aapt resource value: 0x7f0b0059
			public const int distance = 2131427417;
			
			// aapt resource value: 0x7f0b0070
			public const int editText1 = 2131427440;
			
			// aapt resource value: 0x7f0b0073
			public const int etDate = 2131427443;
			
			// aapt resource value: 0x7f0b0034
			public const int etEmail = 2131427380;
			
			// aapt resource value: 0x7f0b0074
			public const int etHour = 2131427444;
			
			// aapt resource value: 0x7f0b0035
			public const int etPassword = 2131427381;
			
			// aapt resource value: 0x7f0b007f
			public const int etStartDate = 2131427455;
			
			// aapt resource value: 0x7f0b0080
			public const int etStartHour = 2131427456;
			
			// aapt resource value: 0x7f0b0081
			public const int etStr = 2131427457;
			
			// aapt resource value: 0x7f0b0084
			public const int flLeaveBlue = 2131427460;
			
			// aapt resource value: 0x7f0b001f
			public const int flReadOnly = 2131427359;
			
			// aapt resource value: 0x7f0b0085
			public const int flReportBlue = 2131427461;
			
			// aapt resource value: 0x7f0b0053
			public const int frameLayout1 = 2131427411;
			
			// aapt resource value: 0x7f0b0078
			public const int framelayout = 2131427448;
			
			// aapt resource value: 0x7f0b0009
			public const int friday = 2131427337;
			
			// aapt resource value: 0x7f0b0012
			public const int horizontal = 2131427346;
			
			// aapt resource value: 0x7f0b0002
			public const int hybrid = 2131427330;
			
			// aapt resource value: 0x7f0b0029
			public const int indicator = 2131427369;
			
			// aapt resource value: 0x7f0b005a
			public const int instruction = 2131427418;
			
			// aapt resource value: 0x7f0b0024
			public const int ivAdd = 2131427364;
			
			// aapt resource value: 0x7f0b0017
			public const int ivBack = 2131427351;
			
			// aapt resource value: 0x7f0b0027
			public const int ivCalendarBack = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int ivCalendarNext = 2131427368;
			
			// aapt resource value: 0x7f0b0069
			public const int ivCredits = 2131427433;
			
			// aapt resource value: 0x7f0b0057
			public const int ivDelete = 2131427415;
			
			// aapt resource value: 0x7f0b0056
			public const int ivEdit = 2131427414;
			
			// aapt resource value: 0x7f0b007b
			public const int ivExtendParkingTime = 2131427451;
			
			// aapt resource value: 0x7f0b0066
			public const int ivMyOwnParking = 2131427430;
			
			// aapt resource value: 0x7f0b0060
			public const int ivParkMe = 2131427424;
			
			// aapt resource value: 0x7f0b0063
			public const int ivReservations = 2131427427;
			
			// aapt resource value: 0x7f0b006b
			public const int ivSetting = 2131427435;
			
			// aapt resource value: 0x7f0b0010
			public const int length_long = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int length_short = 2131427345;
			
			// aapt resource value: 0x7f0b004d
			public const int linearLayout1 = 2131427405;
			
			// aapt resource value: 0x7f0b005e
			public const int linearLayout2 = 2131427422;
			
			// aapt resource value: 0x7f0b002c
			public const int linearLayout3 = 2131427372;
			
			// aapt resource value: 0x7f0b0068
			public const int llCredits = 2131427432;
			
			// aapt resource value: 0x7f0b0065
			public const int llMyOwnParking = 2131427429;
			
			// aapt resource value: 0x7f0b0095
			public const int llMyProfile = 2131427477;
			
			// aapt resource value: 0x7f0b0083
			public const int llNavigate = 2131427459;
			
			// aapt resource value: 0x7f0b005f
			public const int llParkMe = 2131427423;
			
			// aapt resource value: 0x7f0b0062
			public const int llReservations = 2131427426;
			
			// aapt resource value: 0x7f0b0096
			public const int llSetting = 2131427478;
			
			// aapt resource value: 0x7f0b0076
			public const int llStart = 2131427446;
			
			// aapt resource value: 0x7f0b002d
			public const int llVehicle = 2131427373;
			
			// aapt resource value: 0x7f0b0086
			public const int llfullscreen = 2131427462;
			
			// aapt resource value: 0x7f0b0092
			public const int lvSelections = 2131427474;
			
			// aapt resource value: 0x7f0b0075
			public const int map = 2131427445;
			
			// aapt resource value: 0x7f0b0054
			public const int mapView = 2131427412;
			
			// aapt resource value: 0x7f0b0039
			public const int message = 2131427385;
			
			// aapt resource value: 0x7f0b000a
			public const int monday = 2131427338;
			
			// aapt resource value: 0x7f0b0003
			public const int none = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int normal = 2131427332;
			
			// aapt resource value: 0x7f0b003b
			public const int option1 = 2131427387;
			
			// aapt resource value: 0x7f0b003d
			public const int option2 = 2131427389;
			
			// aapt resource value: 0x7f0b003f
			public const int option3 = 2131427391;
			
			// aapt resource value: 0x7f0b0041
			public const int option4 = 2131427393;
			
			// aapt resource value: 0x7f0b0043
			public const int option5 = 2131427395;
			
			// aapt resource value: 0x7f0b0045
			public const int option6 = 2131427397;
			
			// aapt resource value: 0x7f0b0047
			public const int option7 = 2131427399;
			
			// aapt resource value: 0x7f0b0049
			public const int option8 = 2131427401;
			
			// aapt resource value: 0x7f0b004b
			public const int optionCancel = 2131427403;
			
			// aapt resource value: 0x7f0b007c
			public const int parentView = 2131427452;
			
			// aapt resource value: 0x7f0b004c
			public const int progressBar1 = 2131427404;
			
			// aapt resource value: 0x7f0b0023
			public const int realtabcontent = 2131427363;
			
			// aapt resource value: 0x7f0b0089
			public const int relativeLayout1 = 2131427465;
			
			// aapt resource value: 0x7f0b0016
			public const int rlBack = 2131427350;
			
			// aapt resource value: 0x7f0b002b
			public const int rlHeader = 2131427371;
			
			// aapt resource value: 0x7f0b0005
			public const int satellite = 2131427333;
			
			// aapt resource value: 0x7f0b000b
			public const int saturday = 2131427339;
			
			// aapt resource value: 0x7f0b0072
			public const int seekBar1 = 2131427442;
			
			// aapt resource value: 0x7f0b00a3
			public const int stripeCvc = 2131427491;
			
			// aapt resource value: 0x7f0b00a2
			public const int stripeExpiration = 2131427490;
			
			// aapt resource value: 0x7f0b009d
			public const int stripeImage = 2131427485;
			
			// aapt resource value: 0x7f0b00a1
			public const int stripeLastFour = 2131427489;
			
			// aapt resource value: 0x7f0b009e
			public const int stripeLayoutOne = 2131427486;
			
			// aapt resource value: 0x7f0b00a0
			public const int stripeLayoutTwo = 2131427488;
			
			// aapt resource value: 0x7f0b009f
			public const int stripeNumber = 2131427487;
			
			// aapt resource value: 0x7f0b000c
			public const int sunday = 2131427340;
			
			// aapt resource value: 0x7f0b0020
			public const int switch1 = 2131427360;
			
			// aapt resource value: 0x7f0b0052
			public const int tabsText = 2131427410;
			
			// aapt resource value: 0x7f0b0006
			public const int terrain = 2131427334;
			
			// aapt resource value: 0x7f0b0098
			public const int textNeueBold1 = 2131427480;
			
			// aapt resource value: 0x7f0b009a
			public const int textNeueBold2 = 2131427482;
			
			// aapt resource value: 0x7f0b002e
			public const int textView2 = 2131427374;
			
			// aapt resource value: 0x7f0b004f
			public const int textView3 = 2131427407;
			
			// aapt resource value: 0x7f0b0099
			public const int textViewWithFont1 = 2131427481;
			
			// aapt resource value: 0x7f0b008f
			public const int tfCryptogram = 2131427471;
			
			// aapt resource value: 0x7f0b008e
			public const int tfHolderName = 2131427470;
			
			// aapt resource value: 0x7f0b008d
			public const int tfNumber = 2131427469;
			
			// aapt resource value: 0x7f0b000d
			public const int thursday = 2131427341;
			
			// aapt resource value: 0x7f0b0038
			public const int title = 2131427384;
			
			// aapt resource value: 0x7f0b0014
			public const int triangle = 2131427348;
			
			// aapt resource value: 0x7f0b000e
			public const int tuesday = 2131427342;
			
			// aapt resource value: 0x7f0b001d
			public const int tvAdd = 2131427357;
			
			// aapt resource value: 0x7f0b0071
			public const int tvAddASpot = 2131427441;
			
			// aapt resource value: 0x7f0b0091
			public const int tvAddCard = 2131427473;
			
			// aapt resource value: 0x7f0b0030
			public const int tvBuyCredits = 2131427376;
			
			// aapt resource value: 0x7f0b006a
			public const int tvCredits = 2131427434;
			
			// aapt resource value: 0x7f0b001e
			public const int tvDelete = 2131427358;
			
			// aapt resource value: 0x7f0b0058
			public const int tvDistance = 2131427416;
			
			// aapt resource value: 0x7f0b005d
			public const int tvDone = 2131427421;
			
			// aapt resource value: 0x7f0b0032
			public const int tvEdit = 2131427378;
			
			// aapt resource value: 0x7f0b001b
			public const int tvEndDate = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int tvEndTime = 2131427356;
			
			// aapt resource value: 0x7f0b0051
			public const int tvForgotPassword = 2131427409;
			
			// aapt resource value: 0x7f0b0055
			public const int tvGoToSigin = 2131427413;
			
			// aapt resource value: 0x7f0b0033
			public const int tvLogout = 2131427379;
			
			// aapt resource value: 0x7f0b0067
			public const int tvMyOwnParking = 2131427431;
			
			// aapt resource value: 0x7f0b0037
			public const int tvOk = 2131427383;
			
			// aapt resource value: 0x7f0b002a
			public const int tvOnMySpot = 2131427370;
			
			// aapt resource value: 0x7f0b007a
			public const int tvOverview = 2131427450;
			
			// aapt resource value: 0x7f0b0061
			public const int tvParkMe = 2131427425;
			
			// aapt resource value: 0x7f0b0031
			public const int tvPayNow = 2131427377;
			
			// aapt resource value: 0x7f0b0050
			public const int tvPayWithCredits = 2131427408;
			
			// aapt resource value: 0x7f0b008b
			public const int tvPick = 2131427467;
			
			// aapt resource value: 0x7f0b0036
			public const int tvReadTermsOfUse = 2131427382;
			
			// aapt resource value: 0x7f0b0077
			public const int tvRecenter = 2131427447;
			
			// aapt resource value: 0x7f0b0090
			public const int tvRemoveCard = 2131427472;
			
			// aapt resource value: 0x7f0b0093
			public const int tvReport = 2131427475;
			
			// aapt resource value: 0x7f0b0064
			public const int tvReservations = 2131427428;
			
			// aapt resource value: 0x7f0b0082
			public const int tvSearch = 2131427458;
			
			// aapt resource value: 0x7f0b007d
			public const int tvSearchingFor = 2131427453;
			
			// aapt resource value: 0x7f0b009c
			public const int tvSigin = 2131427484;
			
			// aapt resource value: 0x7f0b009b
			public const int tvSignUp = 2131427483;
			
			// aapt resource value: 0x7f0b0079
			public const int tvStart = 2131427449;
			
			// aapt resource value: 0x7f0b0019
			public const int tvStartDate = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int tvStartTime = 2131427354;
			
			// aapt resource value: 0x7f0b0094
			public const int tvTakeAPicture = 2131427476;
			
			// aapt resource value: 0x7f0b0018
			public const int tvTitle = 2131427352;
			
			// aapt resource value: 0x7f0b0022
			public const int tvToday = 2131427362;
			
			// aapt resource value: 0x7f0b008a
			public const int tvValidity = 2131427466;
			
			// aapt resource value: 0x7f0b007e
			public const int tvVehicle = 2131427454;
			
			// aapt resource value: 0x7f0b008c
			public const int tvVehicleManagement = 2131427468;
			
			// aapt resource value: 0x7f0b005c
			public const int tvedit = 2131427420;
			
			// aapt resource value: 0x7f0b006f
			public const int tvfTitle = 2131427439;
			
			// aapt resource value: 0x7f0b0015
			public const int underline = 2131427349;
			
			// aapt resource value: 0x7f0b0013
			public const int vertical = 2131427347;
			
			// aapt resource value: 0x7f0b003a
			public const int view1 = 2131427386;
			
			// aapt resource value: 0x7f0b003c
			public const int view2 = 2131427388;
			
			// aapt resource value: 0x7f0b003e
			public const int view3 = 2131427390;
			
			// aapt resource value: 0x7f0b0040
			public const int view4 = 2131427392;
			
			// aapt resource value: 0x7f0b0042
			public const int view5 = 2131427394;
			
			// aapt resource value: 0x7f0b0044
			public const int view6 = 2131427396;
			
			// aapt resource value: 0x7f0b0046
			public const int view7 = 2131427398;
			
			// aapt resource value: 0x7f0b0048
			public const int view8 = 2131427400;
			
			// aapt resource value: 0x7f0b004a
			public const int viewCancel = 2131427402;
			
			// aapt resource value: 0x7f0b0025
			public const int viewPager = 2131427365;
			
			// aapt resource value: 0x7f0b004e
			public const int webView = 2131427406;
			
			// aapt resource value: 0x7f0b000f
			public const int wednesday = 2131427343;
			
			// aapt resource value: 0x7f0b0021
			public const int weekView = 2131427361;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080002
			public const int default_circle_indicator_orientation = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int default_title_indicator_footer_indicator_style = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int transition_time = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEventView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddSpotAccuracyView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddSpotActivation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddSpotAddressView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AddSpotCalendarTabDay = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AddSpotCalendarTabHost = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int AddSpotCalendarTabMonth = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int AddSpotCalendarTabView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int AddSpotCostView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int AddSpotGoToSpotView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int AddSpotSizeView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int AddSpotView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int AddVehicleView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int AppSettingsView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int BookingView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int BuyCreditView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ChooseVehicleView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int CommonFrament = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int CustomDialog = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int CustomProgressDialog = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int DelayedParkingMapView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Dropdown_Item = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Dropdown_Item_Center = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int DropDownItems = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int DropDownItemsCenter = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int EventDialog = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ExtendParkingTimeConfirmView = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int ExtendParkingTimeView = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ForgotPasswordView = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int IndicatorTabhost = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int InitialMapView = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int ItemAddSpotCalendarView = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int ItemAddSpotSizeView = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int ItemAddSpotView = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int ItemAddVehicleView = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int ItemChooseVehicleView = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int ItemEvent = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int ItemEventCalendarView = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int ItemMyOwnParkingView = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int ItemMyReservationsView = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int ItemParkingExtendTimeView = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int ItemParkingListView = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int ItemReportSelectionView = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int ItemViewPager = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int ItemViewPagerCalendar = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int LeaveParkingView = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int MenuView = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int MessageView = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int month = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int MyOwnParkingView = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int MyProfileView = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int MyReservationsView = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int OwnFragment = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int ParkingListView = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int ParkingMapFragment = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int ParkingMapView = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int ParkingReservedView = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int ParkingSearchView = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int ParkingSearchViewItem = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int ParkingSummaryFragment = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int ParkMeView = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int RentFragment = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int RentProfileView = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int ReportSelectionView = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int ReportView = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int SettingView = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int SignInView = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int SplashScreen = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int stripeviewlayout = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int vpi__tab = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int week = 2130903110;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0d0000
			public const int main = 2131558400;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int doorbell = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060028
			public const int ApplicationName = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int Hello = 2131099687;
			
			// aapt resource value: 0x7f06002d
			public const int action_day_view = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int action_three_day_view = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int action_today = 2131099692;
			
			// aapt resource value: 0x7f06002f
			public const int action_week_view = 2131099695;
			
			// aapt resource value: 0x7f06002a
			public const int app_name = 2131099690;
			
			// aapt resource value: 0x7f060001
			public const int auth_google_play_services_client_facebook_display_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int auth_google_play_services_client_google_display_name = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int common_android_wear_notification_needs_update_text = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int common_android_wear_update_text = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int common_android_wear_update_title = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int common_google_play_services_api_unavailable_text = 2131099679;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_enable_button = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_enable_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_enable_title = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_error_notification_requested_by_msg = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_install_button = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_install_text_phone = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_install_text_tablet = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_title = 2131099655;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_invalid_account_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_invalid_account_title = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_needs_enabling_title = 2131099653;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_network_error_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_network_error_title = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_notification_needs_update_title = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_notification_ticker = 2131099650;
			
			// aapt resource value: 0x7f060021
			public const int common_google_play_services_sign_in_failed_text = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int common_google_play_services_sign_in_failed_title = 2131099680;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_unknown_issue = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_unsupported_text = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_unsupported_title = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_update_button = 2131099675;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_update_text = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_update_title = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_updating_text = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_updating_title = 2131099666;
			
			// aapt resource value: 0x7f06001e
			public const int common_open_on_phone = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int common_signin_button_text = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int common_signin_button_text_long = 2131099677;
			
			// aapt resource value: 0x7f060023
			public const int day_name_format = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int full_date_format = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int hello = 2131099689;
			
			// aapt resource value: 0x7f060024
			public const int invalid_date = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int library_name = 2131099682;
			
			// aapt resource value: 0x7f060025
			public const int month_name_format = 2131099685;
			
			// aapt resource value: 0x7f06002b
			public const int readtermsofuse = 2131099691;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0005
			public const int AppBaseTheme = 2131361797;
			
			// aapt resource value: 0x7f0a0001
			public const int CalendarCell = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int CalendarCell_CalendarDate = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int CalendarCell_DayHeader = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int CalendarTitle = 2131361792;
			
			// aapt resource value: 0x7f0a000b
			public const int CustomCirclePageIndicator = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int CustomTabPageIndicator = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int CustomTabPageIndicator_Text = 2131361805;
			
			// aapt resource value: 0x7f0a000a
			public const int CustomTitlePageIndicator = 2131361802;
			
			// aapt resource value: 0x7f0a000e
			public const int DialogAnimation = 2131361806;
			
			// aapt resource value: 0x7f0a0008
			public const int RobotoButtonStyle = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int RobotoTextViewStyle = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int StyledIndicators = 2131361801;
			
			// aapt resource value: 0x7f0a0015
			public const int TextAppearance_TabPageIndicator = 2131361813;
			
			// aapt resource value: 0x7f0a000f
			public const int Theme_PageIndicatorDefaults = 2131361807;
			
			// aapt resource value: 0x7f0a0004
			public const int Theme_UserDialog = 2131361796;
			
			// aapt resource value: 0x7f0a0010
			public const int Widget = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int Widget_CirclePageIndicator = 2131361809;
			
			// aapt resource value: 0x7f0a0013
			public const int Widget_TabPageIndicator = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int Widget_TabPageIndicator_Text = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int Widget_TitlePageIndicator = 2131361810;
			
			// aapt resource value: 0x7f0a0006
			public const int mySpinnerStyle = 2131361798;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CalendarPickerView = new int[]
			{
					16842964,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 0
			public const int CalendarPickerView_android_background = 0;
			
			// aapt resource value: 2
			public const int CalendarPickerView_dayBackground = 2;
			
			// aapt resource value: 3
			public const int CalendarPickerView_dayTextColor = 3;
			
			// aapt resource value: 1
			public const int CalendarPickerView_dividerColor = 1;
			
			// aapt resource value: 5
			public const int CalendarPickerView_headerTextColor = 5;
			
			// aapt resource value: 4
			public const int CalendarPickerView_titleTextColor = 4;
			
			public static int[] CirclePageIndicator = new int[]
			{
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] MvxBinding = new int[]
			{
					2130772021,
					2130772022};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxImageView = new int[]
			{
					2130772026};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130772023,
					2130772024,
					2130772025};
			
			// aapt resource value: 2
			public const int MvxListView_GroupItemTemplate = 2;
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] TitlePageIndicator = new int[]
			{
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130772027,
					2130772028,
					2130772029,
					2130772030};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 2;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTabTextStyle = 3;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 1;
			
			public static int[] WeekView = new int[]
			{
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020};
			
			// aapt resource value: 6
			public const int WeekView_columnGap = 6;
			
			// aapt resource value: 10
			public const int WeekView_dayBackgroundColor = 10;
			
			// aapt resource value: 18
			public const int WeekView_dayNameLength = 18;
			
			// aapt resource value: 20
			public const int WeekView_eventMarginVertical = 20;
			
			// aapt resource value: 16
			public const int WeekView_eventPadding = 16;
			
			// aapt resource value: 15
			public const int WeekView_eventTextColor = 15;
			
			// aapt resource value: 3
			public const int WeekView_eventTextSize = 3;
			
			// aapt resource value: 0
			public const int WeekView_firstDayOfWeek = 0;
			
			// aapt resource value: 17
			public const int WeekView_headerColumnBackground = 17;
			
			// aapt resource value: 4
			public const int WeekView_headerColumnPadding = 4;
			
			// aapt resource value: 7
			public const int WeekView_headerColumnTextColor = 7;
			
			// aapt resource value: 9
			public const int WeekView_headerRowBackgroundColor = 9;
			
			// aapt resource value: 5
			public const int WeekView_headerRowPadding = 5;
			
			// aapt resource value: 1
			public const int WeekView_hourHeight = 1;
			
			// aapt resource value: 11
			public const int WeekView_hourSeparatorColor = 11;
			
			// aapt resource value: 14
			public const int WeekView_hourSeparatorHeight = 14;
			
			// aapt resource value: 8
			public const int WeekView_noOfVisibleDays = 8;
			
			// aapt resource value: 19
			public const int WeekView_overlappingEventGap = 19;
			
			// aapt resource value: 2
			public const int WeekView_textSizeX = 2;
			
			// aapt resource value: 12
			public const int WeekView_todayBackgroundColor = 12;
			
			// aapt resource value: 13
			public const int WeekView_todayHeaderTextColor = 13;
			
			// aapt resource value: 21
			public const int WeekView_xScrollingSpeed = 21;
			
			public static int[] calendar_cell = new int[]
			{
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 1
			public const int calendar_cell_state_current_month = 1;
			
			// aapt resource value: 6
			public const int calendar_cell_state_highlighted = 6;
			
			// aapt resource value: 3
			public const int calendar_cell_state_range_first = 3;
			
			// aapt resource value: 5
			public const int calendar_cell_state_range_last = 5;
			
			// aapt resource value: 4
			public const int calendar_cell_state_range_middle = 4;
			
			// aapt resource value: 0
			public const int calendar_cell_state_selectable = 0;
			
			// aapt resource value: 2
			public const int calendar_cell_state_today = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
