#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonoDroid.TimesSquare.Resource", IsApplication=false)]

namespace MonoDroid.TimesSquare
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int dayBackground = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int dayTextColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int dividerColor = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int headerTextColor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int state_current_month = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public static int state_highlighted = 2130771979;
			
			// aapt resource value: 0x7f010008
			public static int state_range_first = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public static int state_range_last = 2130771978;
			
			// aapt resource value: 0x7f010009
			public static int state_range_middle = 2130771977;
			
			// aapt resource value: 0x7f010005
			public static int state_selectable = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int state_today = 2130771975;
			
			// aapt resource value: 0x7f010003
			public static int titleTextColor = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public static int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public static int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public static int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public static int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public static int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public static int calendar_text_selector = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public static int calendar_text_unselectable = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int calendar_today_bg = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int calendar_text_small = 2131034116;
			
			// aapt resource value: 0x7f050021
			public static int marginBase = 2131034145;
			
			// aapt resource value: 0x7f050022
			public static int marginBase_5 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public static int marginBase_6 = 2131034147;
			
			// aapt resource value: 0x7f050017
			public static int marginBasex10 = 2131034135;
			
			// aapt resource value: 0x7f050016
			public static int marginBasex11 = 2131034134;
			
			// aapt resource value: 0x7f050015
			public static int marginBasex12 = 2131034133;
			
			// aapt resource value: 0x7f050014
			public static int marginBasex13 = 2131034132;
			
			// aapt resource value: 0x7f050013
			public static int marginBasex14 = 2131034131;
			
			// aapt resource value: 0x7f050012
			public static int marginBasex15 = 2131034130;
			
			// aapt resource value: 0x7f050011
			public static int marginBasex18 = 2131034129;
			
			// aapt resource value: 0x7f050020
			public static int marginBasex2 = 2131034144;
			
			// aapt resource value: 0x7f050010
			public static int marginBasex20 = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public static int marginBasex22 = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public static int marginBasex23 = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public static int marginBasex25 = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public static int marginBasex27 = 2131034124;
			
			// aapt resource value: 0x7f05001f
			public static int marginBasex3 = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public static int marginBasex3_5 = 2131034142;
			
			// aapt resource value: 0x7f05000b
			public static int marginBasex30 = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public static int marginBasex35 = 2131034122;
			
			// aapt resource value: 0x7f05001d
			public static int marginBasex4 = 2131034141;
			
			// aapt resource value: 0x7f050009
			public static int marginBasex40 = 2131034121;
			
			// aapt resource value: 0x7f050008
			public static int marginBasex45 = 2131034120;
			
			// aapt resource value: 0x7f05001c
			public static int marginBasex5 = 2131034140;
			
			// aapt resource value: 0x7f050007
			public static int marginBasex50 = 2131034119;
			
			// aapt resource value: 0x7f050006
			public static int marginBasex55 = 2131034118;
			
			// aapt resource value: 0x7f05001b
			public static int marginBasex6 = 2131034139;
			
			// aapt resource value: 0x7f050005
			public static int marginBasex60 = 2131034117;
			
			// aapt resource value: 0x7f05001a
			public static int marginBasex7 = 2131034138;
			
			// aapt resource value: 0x7f050019
			public static int marginBasex8 = 2131034137;
			
			// aapt resource value: 0x7f050018
			public static int marginBasex9 = 2131034136;
			
			// aapt resource value: 0x7f05002f
			public static int menu_width = 2131034159;
			
			// aapt resource value: 0x7f050026
			public static int textBig = 2131034150;
			
			// aapt resource value: 0x7f050025
			public static int textBigger = 2131034149;
			
			// aapt resource value: 0x7f050028
			public static int textExtraLarge = 2131034152;
			
			// aapt resource value: 0x7f05002d
			public static int textExtraSmall = 2131034157;
			
			// aapt resource value: 0x7f050024
			public static int textHeader = 2131034148;
			
			// aapt resource value: 0x7f050029
			public static int textLarge = 2131034153;
			
			// aapt resource value: 0x7f05002b
			public static int textMedium = 2131034155;
			
			// aapt resource value: 0x7f050027
			public static int textMediumBig = 2131034151;
			
			// aapt resource value: 0x7f05002a
			public static int textMediumLarge = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public static int textSmall = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public static int textXXSmall = 2131034158;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int calendar_bg_selector = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public static int calendar_grid = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int title = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int month = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int week = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public static int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public static int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060002
			public static int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public static int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public static int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public static int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CalendarPickerView = new int[]
			{
					16842964,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public static int CalendarPickerView_android_background = 0;
			
			// aapt resource value: 2
			public static int CalendarPickerView_dayBackground = 2;
			
			// aapt resource value: 3
			public static int CalendarPickerView_dayTextColor = 3;
			
			// aapt resource value: 1
			public static int CalendarPickerView_dividerColor = 1;
			
			// aapt resource value: 5
			public static int CalendarPickerView_headerTextColor = 5;
			
			// aapt resource value: 4
			public static int CalendarPickerView_titleTextColor = 4;
			
			public static int[] calendar_cell = new int[]
			{
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public static int calendar_cell_state_current_month = 1;
			
			// aapt resource value: 6
			public static int calendar_cell_state_highlighted = 6;
			
			// aapt resource value: 3
			public static int calendar_cell_state_range_first = 3;
			
			// aapt resource value: 5
			public static int calendar_cell_state_range_last = 5;
			
			// aapt resource value: 4
			public static int calendar_cell_state_range_middle = 4;
			
			// aapt resource value: 0
			public static int calendar_cell_state_selectable = 0;
			
			// aapt resource value: 2
			public static int calendar_cell_state_today = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
